const debtop=[
"Animal testing does more good than harm.",
"Animal testing is unethical.",
"Asian Oyster seeding in the Chesapeake Bay should be banned.",
"Ban plastic bags in grocery stores.",
"Bottled water causes more harm than good.",
"Desert area residents should be required to use desert landscaping.",
"End Daylight Savings time.",
"Extra-terrestrial intelligence exists.",
"Factory farming does more harm than good.",
"Genetically modified foods cause more good than harm.",
"Human cloning should be permitted in the United States.",
"Human genome sequencing does more harm than good.",
"Hydrofracking does more harm than good.",
"Immunizations should not be mandated.",
"It is morally acceptable to experiment on animals for medical purposes.",
"Legalize human organ sales.",
"Media Coverage of Ebola does more harm than good.",
"Medical testing on animals does more good than harm.",
"New Jersey should end the bear hunt.",
"New York City should not build sea barriers.",
"No space exploration should be permitted without showing that it will not harm extraterrestrial microbial life.",
"On balance, nuclear energy does more good than harm.",
"Organ donation should be compulsory for all United States citizens.",
"Physician-assisted suicide should be legalized.",
"Schools should ban animal dissection.",
"South Jersey Gas should be allowed to build a pipeline through the Pinelands.",
"State mandated administration of childhood vaccines is justified.",
"Stem cell research should be expanded.",
"The Endangered Species Act should no longer include exemptions for subsistence or traditional use.",
"The FDA should ban the domestic sale of foods that include GMOs.",
"The FDA should increase the frequency with which they inspect meat.",
"The international community should ban nuclear-powered spacecraft.",
"The Obama administration should approve the Keystone pipeline.",
"The U.S. should not send humans into space.",
"The U.S. Space Program should be privatized",
"The United States Federal Government should ban production of genetically modified organisms(GMO's).",
"The United States should expand its use of nuclear power.",
"The United States should increase its use of solar power.",
"The United States should not expand drilling for oil off the East Coast.",
"The United States should not send humans into space.",
"The US should establish a national DNA database of all residents.",
"The United States should significantly increase space exploration.",
"Zoos do more harm than good."  
];

module.exports.debtop=debtop;